# Generated by Django 4.0.4 on 2022-04-20 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('comment', models.CharField(max_length=60)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('precision', models.FloatField()),
                ('population', models.FloatField()),
                ('quality', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60)),
                ('UID', models.CharField(max_length=60)),
                ('isAdmin', models.BooleanField(default=False)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
        migrations.AddField(
            model_name='opinion',
            name='IDplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_App.place'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='IDuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_App.user'),
        ),
    ]
