# Generated by Django 4.0.4 on 2022-04-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0002_opinion_place_user_delete_hero_opinion_idplace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UID',
            field=models.CharField(max_length=100),
        ),
    ]
