# Generated by Django 3.2.5 on 2022-04-23 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0003_alter_user_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDopinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_App.opinion')),
                ('IDuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_App.user')),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('timeStart', models.TimeField()),
                ('timeEnd', models.TimeField()),
                ('IDplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_App.place')),
                ('IDuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_App.user')),
            ],
        ),
        migrations.CreateModel(
            name='Place_Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDopinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_App.opinion')),
                ('IDplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_App.place')),
            ],
        ),
    ]
