# Generated by Django 3.2.5 on 2022-04-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0004_place_opinion_presence_user_opinion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='address',
        ),
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
