# Generated by Django 3.2.5 on 2022-04-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0007_spot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='ERP_cat',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='hauteur_aire',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='largeur_aire',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='longueur_aire',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='nb_equipements',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='nb_places_parking',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='nb_places_parking_handicap',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='places_tribune',
            field=models.IntegerField(null=True),
        ),
    ]
