# Generated by Django 3.2.5 on 2022-05-02 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0012_auto_20220502_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spot',
            old_name='code20120',
            new_name='code2016',
        ),
    ]
