# Generated by Django 3.2.5 on 2022-05-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0014_auto_20220502_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='nominstallation',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
