# Generated by Django 3.2.5 on 2022-05-10 07:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0016_auto_20220502_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point_spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_coord', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('spot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_App.spot')),
            ],
        ),
    ]
