# Generated by Django 3.2.5 on 2022-05-11 17:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0019_rename_pointcoord_point_spot_point_coord_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='point_coord_spot',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.DeleteModel(
            name='Point_spot',
        ),
    ]
